### ISSUE TITLE
## Stack:  UI Tests

### ISSUE THREAD

**Issue by nimaai** [leihs/leihs-borrow#8]
***
@nimaai / @mfa
***

Evaluate by example: Cypress
see https://docs.cypress.io/

- setup Cypress to run locally
- [ ] write an E2E feature spec (like api-based spec "search&order")
- [ ] try out ClojureScript integration
- [ ] FactoryBot ?

https://github.com/teamcapybara/capybara#apparition

**Comment by nimaai** [comment]
@eins78 let's decide what to do next.

**Comment by eins78** [comment]
lets stay with rspec/capybara/turnip/gherkin
